# Используем Python 3.11 slim
FROM python:3.11-slim

# Рабочая директория внутри контейнера
WORKDIR /app

# Копируем все файлы проекта в контейнер
COPY . /app

# Обновляем pip и устанавливаем зависимости
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Переменные окружения (не секретные)
ENV PYTHONUNBUFFERED=1

# Команда для запуска бота
CMD ["python", "bot.py"]

