# Используем Python 3.11 slim
FROM python:3.11-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта
COPY . /app

# Обновляем pip и устанавливаем зависимости
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Устанавливаем переменные окружения (не секретные)
ENV PYTHONUNBUFFERED=1

# Команда по умолчанию (можно заменить на запуск вашего бота)
CMD ["python", "bot.py"]


