# Базовый образ с Python 3.11
FROM python:3.11-slim

# Создаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта
COPY . /app

# Устанавливаем зависимости в виртуальной среде
RUN python -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip \
    && /opt/venv/bin/pip install --no-cache-dir -r requirements.txt

# Добавляем venv в PATH
ENV PATH="/opt/venv/bin:$PATH"

# Опция для логирования Python сразу (без буферизации)
ENV PYTHONUNBUFFERED=1

# Команда запуска
CMD ["python", "bot.py"]



